services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data
      - media_data:/app/media
      - static_data:/app/staticfiles
    environment:
      - SQLITE_DB_DIR=data
    ports:
      - "8000:8000"

volumes:
  sqlite_data:
  media_data:
  static_data:
